version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./docker/nginx/site.template:/etc/nginx/conf.d/site.template
      - ./:/app
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=app.local
    links:
      - php
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_HOST' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  php:
    build: ./docker/php
    volumes:
      - ./:/app
